export const ENV = {
  production: true,
  apiUrl: "https://api-stage.legalnav.org/api",
  bingmap_key: "AoJiv5Zm4MxwY45PlkVGv893kDc404xvIjxKmE5JP1T0Ma7JlSjCQ-9Wi4cpkLTV",
  map_type: false,
  internalResourcePagesToShow: 2,
  internalResourceRecordsToDisplay: 10,
  webResourcePagesToShow: 10,
  webResourceRecordsToDisplay: 10,
  blobUrl: "https://legalnavstagestor.blob.core.windows.net",
  virtualEarthUrl: "https://dev.virtualearth.net/REST/v1/Locations/",
  All: "All",
  clientID: "110cf200-fc79-4551-8008-3a2eff53637b",
  authority: "https://login.microsoftonline.com/common/",
  consentScopes: ["api://110cf200-fc79-4551-8008-3a2eff53637b/access_as_user"],
  redirectUri: "https://stage.legalnav.org/",
  navigateToLoginRequestUrl: true,
  postLogoutRedirectUri: "https://stage.legalnav.org/",
  topicUrl: "https://api-stage.legalnav.org/api/topics",
  userPersonalizedPlanUrl: "https://api-stage.legalnav.org/api/user/upsertuserpersonalizedplan",
  apiScope: "api://110cf200-fc79-4551-8008-3a2eff53637b/access_as_user"
};
