export default {
  production: false,
  apiUrl: "https://api-dev.legalnav.org/api",
  bingmap_key: "AkaN9T4QD5xmxp3PbDCeEmnIi-BDrMd7Hi4Lp8P_orTTQ2L_s1QKSumVBlefNKrk",
  map_type: false,
  internalResourcePagesToShow: 2,
  internalResourceRecordsToDisplay: 10,
  webResourcePagesToShow: 10,
  webResourceRecordsToDisplay: 10,
  blobUrl: "https://legalnavdevstor.blob.core.windows.net",
  virtualEarthUrl: "https://dev.virtualearth.net/REST/v1/Locations/",
  All: "All",
  clientID: "d528c88c-301c-4a5c-8967-96d571a5be96",
  authority: "https://login.microsoftonline.com/common/",
  consentScopes: ["api://d528c88c-301c-4a5c-8967-96d571a5be96/access_as_user"],
  redirectUri: "https://dev.legalnav.org/",
  navigateToLoginRequestUrl: true,
  postLogoutRedirectUri: "https://dev.legalnav.org/",
  topicUrl: "https://api-dev.legalnav.org/api/topics",
  userPersonalizedPlanUrl: "https://api-dev.legalnav.org/api/user/upsertuserpersonalizedplan",
  apiScope: "api://d528c88c-301c-4a5c-8967-96d571a5be96/access_as_user"
};
