export const environment = {
  production: true,
  apiUrl: 'https://access2justiceapi.azurewebsites.net/api',
  bingmap_key: 'AlyLqEyg06sSOQJUwYsqcsm69zWmVKYgmaGvqdBPISKCJ59IQqqfCCaQ42KgqTyG',
  map_type: false,
  internalResourcePagesToShow: 2,
  internalResourceRecordsToDisplay: 10,
  webResourcePagesToShow: 10,
  webResourceRecordsToDisplay: 10,
  blobUrl: 'https://cs4892808efec24x447cx944.blob.core.windows.net',
  virtualEarthUrl: 'https://dev.virtualearth.net/REST/v1/Locations/',
  All: 'All',
  clientID: 'b0e337fd-7807-4446-9928-a61aecaf1d39',
  authority: 'https://login.microsoftonline.com/common/',
  consentScopes: ["api://b0e337fd-7807-4446-9928-a61aecaf1d39/access_as_user"],
  redirectUri: 'https://a2jdevweb.azurewebsites.net/',
  navigateToLoginRequestUrl: true,
  postLogoutRedirectUri: 'https://a2jdevweb.azurewebsites.net/',
  topicUrl: 'https://access2justiceapi.azurewebsites.net/api/topics',
  userPersonalizedPlanUrl: 'https://access2justiceapi.azurewebsites.net/api/user/upsertuserpersonalizedplan',
  apiScope: 'api://b0e337fd-7807-4446-9928-a61aecaf1d39/access_as_user'
};
