import { Topic } from "../topics-resources/topic";

export const TOPICS: Topic[] = [
//  {image: './assets/images/topics/topic1.png', title: 'Eviction', url:'www.google.com'},
//  {image: './assets/images/topics/topic2.png', title: 'Child Custody', url:'www.google.com'},
//  {image: './assets/images/topics/topic3.png', title: 'Domestic Violence', url:'www.google.com'},
//  {image: './assets/images/topics/topic4.png', title: 'Divorce', url:'www.google.com'},
//  {image: './assets/images/topics/topic5.png', title: 'Debt Collection', url:'www.google.com'},
//  {image: './assets/images/topics/topic6.png', title: 'Successions/Probate', url:'www.google.com'},
//  {image: './assets/images/topics/topic7.png', title: 'Eviction', url:'www.google.com'},
//  {image: './assets/images/topics/topic8.png', title: 'Child Custody', url:'www.google.com'},
//  {image: './assets/images/topics/topic9.png', title: 'Domestic Violence', url:'www.google.com'},
//  {image: './assets/images/topics/topic10.png', title: 'Divorce', url:'www.google.com'},
//  {image: './assets/images/topics/topic11.png', title: 'Debt Collection', url:'www.google.com'},
//  {image: './assets/images/topics/topic12.png', title: 'Successions/Probate', url:'www.google.com'},
//  {image: './assets/images/topics/topic13.png', title: 'Eviction', url:'www.google.com'},
//  {image: './assets/images/topics/topic14.png', title: 'Child Custody', url:'www.google.com'},
//  {image: './assets/images/topics/topic15.png', title: 'Domestic Violence', url:'www.google.com'},
//  {image: './assets/images/topics/topic16.png', title: 'Divorce', url:'www.google.com'},
//  {image: './assets/images/topics/topic17.png', title: 'Debt Collection', url:'www.google.com'},
//  {image: './assets/images/topics/topic18.png', title: 'Successions/Probate', url:'www.google.com'},
//  {image: './assets/images/topics/topic19.png', title: 'Eviction', url:'www.google.com'},
//  {image: './assets/images/topics/topic20.png', title: 'Child Custody', url:'www.google.com'},
//  {image: './assets/images/topics/topic21.png', title: 'Domestic Violence', url:'www.google.com'},
//  {image: './assets/images/topics/topic22.png', title: 'Divorce', url:'www.google.com'},
//  {image: './assets/images/topics/topic23.png', title: 'Debt Collection', url:'www.google.com'},
//  {image: './assets/images/topics/topic24.png', title: 'Successions/Probate', url:'www.google.com'},
//  {image: './assets/images/topics/topic25.png', title: 'Eviction', url:'www.google.com'},
//  {image: './assets/images/topics/topic26.png', title: 'Child Custody', url:'www.google.com'},
//  {image: './assets/images/topics/topic27.png', title: 'Domestic Violence', url:'www.google.com'},
//  {image: './assets/images/topics/topic28.png', title: 'Divorce', url:'www.google.com'},
//  {image: './assets/images/topics/topic29.png', title: 'Debt Collection', url:'www.google.com'},
//  {image: './assets/images/topics/topic30.png', title: 'Successions/Probate', url:'www.google.com'}
];
